# Generated by Django 3.2.7 on 2023-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dmchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmchat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
