# Generated by Django 3.2.7 on 2023-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dmchat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmchat',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
